require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'src/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/swagger_helper.rb'
    - 'spec/*/*_spec.rb'
    - 'spec/factories/*.rb'
    - 'db/*.rb'
    - 'db/migrate/*.rb'
    - 'config.ru'
    - 'bin/*'
    - 'storage/**/*'
    - 'lib/tasks/pocs/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

Layout/LineLength:
  Exclude:
    - spec/**/*
    - config/initializers/*.rb

# Disable the hard ones for the time beeing
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: only_before

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

