---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/pub/pages":
    get:
      summary: list pages
      produces:
      - application/json
      responses:
        '200':
          description: pages found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                url:
                  type: string
                audit_frequency:
                  type: string
                  enum:
                  - hourly
                  - daily
                status:
                  type: string
                  enum:
                  - active
                  - inactive
                  - archived
