---
swagger: '2.0'
info:
  title: Phare API
  description: 'Phare API: A Web Performance Monitoring API, driven by Google PageSpeed
    Insights API and powered by Ruby On Rails'
  version: v1
paths:
  "/api/v1/pub/pages":
    put:
      summary: add or requeue page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: page
        in: body
        schema:
          type: object
          properties:
            url:
              type: string
            audit_frequency:
              type: string
              enum:
              - hourly
              - daily
          required:
          - url
      responses:
        '200':
          description: page created and requeued
        '400':
          description: invalid url
    get:
      summary: list pages
      produces:
      - application/json
      responses:
        '200':
          description: pages found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                url:
                  type: string
                audit_frequency:
                  type: string
                  enum:
                  - hourly
                  - daily
                status:
                  type: string
                  enum:
                  - active
                  - inactive
                  - archived
  "/api/v1/pub/pages/{id}":
    get:
      summary: get page
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: page found
          schema:
            type: object
            properties:
              id:
                type: integer
              url:
                type: string
              audit_frequency:
                type: string
                enum:
                - hourly
                - daily
              status:
                type: string
                enum:
                - active
                - inactive
                - archived
        '404':
          description: page not found
  "/api/v1/pub/pages/{id}/statistics":
    get:
      summary: get statistics of page
      deprecated: true
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: page found
          schema:
            type: array
            items:
              type: object
              properties:
                day:
                  type: string
                mpf:
                  type: number
                fmp:
                  type: number
                fci:
                  type: number
                fcp:
                  type: number
                si:
                  type: number
                ia:
                  type: number
        '404':
          description: page not found
securityDefinitions:
  apiKey:
    type: apiKey
    name: key
    in: query
