---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/pub/pages":
    put:
      summary: add or requeue page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: page
        in: body
        schema:
          type: object
          properties:
            url:
              type: string
            audit_frequency:
              type: string
          required:
          - url
      responses:
        '200':
          description: page created and requeued
    get:
      summary: list pages
      produces:
      - application/json
      responses:
        '200':
          description: pages found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                url:
                  type: string
                audit_frequency:
                  type: string
                  enum:
                  - hourly
                  - daily
                status:
                  type: string
                  enum:
                  - active
                  - inactive
                  - archived
  "/api/v1/pub/pages/{id}":
    get:
      summary: get page
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: page found
          schema:
            type: object
            properties:
              id:
                type: integer
              url:
                type: string
              audit_frequency:
                type: string
                enum:
                - hourly
                - daily
              status:
                type: string
                enum:
                - active
                - inactive
                - archived
        '404':
          description: page not found
