---
swagger: '2.0'
info:
  title: Phare API
  description: 'Phare API: A Web Performance Monitoring API, driven by Google PageSpeed
    Insights API and powered by Ruby On Rails'
  version: v1
paths:
  "/api/v1/pub/pages/{page_id}/audit_reports":
    get:
      summary: list audit reports of page
      produces:
      - application/json
      parameters:
      - name: page_id
        in: path
        type: string
        required: true
      - name: fields[auditReports]
        in: query
        type: array
        required: false
        collectionFormat: csv
        description: 'sparese fields. lighthouseResult: add lighthouse json to the
          response'
        items:
          type: string
          enum:
          - lighthouseResult
      - name: page[limit]
        in: query
        type: integer
        required: false
        description: limit number of returned audit reports
      responses:
        '200':
          description: audit reports found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                auditType:
                  type: string
                  enum:
                  - psi
                  - lighthouse
                summary:
                  type: object
                  properties:
                    fetchTime:
                      type: string
                      format: date-time
                    max-potential-fid:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                    first-meaningful-paint:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                    first-cpu-idle:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                    first-contentful-paint:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                    speed-index:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                    interactive:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        numericValue:
                          type: number
                        displayValue:
                          type: string
                lighthouseResult:
                  type: object
                  properties: {}
                  x-nullable: true
              required:
              - id
              - auditType
              - summary
  "/api/v1/pub/pages/{page_id}/audit_reports/{audit_report_id}":
    get:
      summary: get audit report of page
      produces:
      - application/json
      parameters:
      - name: page_id
        in: path
        type: string
        required: true
      - name: audit_report_id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: audit report found
          schema:
            type: object
            properties:
              id:
                type: integer
              auditType:
                type: string
                enum:
                - psi
                - lighthouse
              summary:
                type: object
                properties:
                  fetchTime:
                    type: string
                    format: date-time
                  max-potential-fid:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
                  first-meaningful-paint:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
                  first-cpu-idle:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
                  first-contentful-paint:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
                  speed-index:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
                  interactive:
                    type: object
                    properties:
                      id:
                        type: string
                      score:
                        type: number
                      numericValue:
                        type: number
                      displayValue:
                        type: string
              lighthouseResult:
                type: object
                properties: {}
                x-nullable: true
            required:
            - id
            - auditType
            - summary
  "/api/v1/pub/labels":
    get:
      summary: list labels
      produces:
      - application/json
      responses:
        '200':
          description: labels found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                color:
                  type: string
              required:
              - id
              - name
              - color
    post:
      summary: create label
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: label
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            color:
              type: string
          required:
          - name
      responses:
        '201':
          description: label created
  "/api/v1/pub/labels/{id}":
    get:
      summary: get label
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: label found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              color:
                type: string
            required:
            - id
            - name
            - color
        '404':
          description: label not found
    put:
      summary: update label
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: label
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            color:
              type: string
      responses:
        '200':
          description: label updated
        '404':
          description: label not found
  "/api/v1/pub/pages":
    put:
      summary: add or requeue page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: page
        in: body
        schema:
          type: object
          properties:
            url:
              type: string
            audit_frequency:
              type: string
              enum:
              - hourly
              - daily
          required:
          - url
      responses:
        '200':
          description: page created and requeued
        '400':
          description: invalid url
    get:
      summary: list pages
      produces:
      - application/json
      parameters:
      - name: include
        in: query
        type: array
        required: false
        collectionFormat: csv
        description: include associations of pages, e.g. label
        items:
          type: string
          enum:
          - label
      - name: filter[label]
        in: query
        type: array
        required: false
        collectionFormat: csv
        description: filter for pages with specific label IDs
        items:
          type: number
      responses:
        '200':
          description: pages found
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                url:
                  type: string
                auditFrequency:
                  type: string
                  enum:
                  - hourly
                  - daily
                status:
                  type: string
                  enum:
                  - active
                  - inactive
                  - archived
                lastAuditedAt:
                  type: string
                  format: date-time
                  x-nullable: true
                label:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
              required:
              - id
              - url
              - auditFrequency
              - status
              - lastAuditedAt
  "/api/v1/pub/pages/{id}":
    get:
      summary: get page
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: include
        in: query
        type: array
        required: false
        collectionFormat: csv
        description: include associations of pages, e.g. label
        items:
          type: string
          enum:
          - label
      responses:
        '200':
          description: page found
          schema:
            type: object
            properties:
              id:
                type: integer
              url:
                type: string
              auditFrequency:
                type: string
                enum:
                - hourly
                - daily
              status:
                type: string
                enum:
                - active
                - inactive
                - archived
              lastAuditedAt:
                type: string
                format: date-time
                x-nullable: true
              label:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  color:
                    type: string
            required:
            - id
            - url
            - auditFrequency
            - status
            - lastAuditedAt
        '404':
          description: page not found
  "/api/v1/pub/pages/{id}/statistics":
    get:
      summary: get statistics of page
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: page found
          schema:
            type: array
            items:
              type: object
              properties:
                day:
                  type: string
                max_potential_fid:
                  type: number
                first_meaningful_paint:
                  type: number
                first_cpu_idle:
                  type: number
                first_contentful_paint:
                  type: number
                speed_index:
                  type: number
                interactive:
                  type: number
        '404':
          description: page not found
  "/api/v1/pub/pages/{id}/label":
    put:
      summary: assign label to page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: label
        in: body
        schema:
          type: object
          properties:
            label:
              type: object
              properties:
                id:
                  type: integer
          required:
          - label
      responses:
        '200':
          description: label assigned
        '400':
          description: invalid payload
        '404':
          description: page or label not found
securityDefinitions:
  apiKey:
    type: apiKey
    name: key
    in: query
